# Site settings
title: H. Tyler  Brooks
email: htb5qh@gmail.com
url: https://example.github.io
description: "Full Stack Web Developer Looking For a Place to Grow and Develop My Skills"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/htylerbrooks
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=425203738&trk=nav_responsive_tab_profile
  - title: github
    url: https://github.com/htylerbrooks

# Build settings
markdown: kramdown
permalink: pretty
